export const UPDATE_PERSONAL_INFO = "UPDATE_PERSONAL_INFO";
export const UPDATE_WORKSPACE_INFO = "UPDATE_WORKSPACE_INFO";
export const UPDATE_EDEN_PLAN = "UPDATE_EDEN_PLAN";
export const UPDATE_STEPPER = "UPDATE_STEPPER";
